version: "3"

services:
  # CORE SERVICES
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    mem_limit: 512m
    mem_reservation: 128M
  redis:
    image: redis
    mem_limit: 512m
    mem_reservation: 128M

  # FRONTEND
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"

  # Backend API
  api:
    build: ./api
    image: shoe-store_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
      - gems:/gems
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  sidekiq:
    image: shoe-store_api
    command: "sidekiq -C config/sidekiq.yml"
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
  receiver:
    image: shoe-store_api
    command: bin/rails r receiver.rb
    depends_on:
      - db
      - redis
      - sender
    volumes:
      - ./api:/app
    mem_limit: 128M
    mem_reservation: 64M
  sender:
    build: ./websocket
    command: bin/websocketd --port=8080 ruby inventory.rb
    volumes:
      - ./websocket:/sender
    ports:
      - "8080:8080"
    mem_limit: 128M
    mem_reservation: 64M
volumes:
  postgres:
  gems:
